var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var brcaInfoSchema= new Schema({
    a260_a280_ratio: Number,
    age_at_diagnosis: Number,
    ajcc_metastasis_pathologic_pm: String,
    ajcc_nodes_pathologic_pn: String,
    ajcc_pathologic_tumor_stage: String,
    ajcc_staging_edition: String,
    ajcc_tumor_pathologic_pt: String,
    analyte_type: String,
    analyte_type_id: String,
    anatomic_neoplasm_subdivision: String,
    axillary_staging_method: String,
    bcr_aliquot_barcode: String,
    bcr_aliquot_uuid: String,
    bcr_analyte_barcode: String,
    bcr_analyte_uuid: String,
    bcr_patient_barcode: String,
    bcr_patient_uuid: String,
    bcr_portion_barcode: String,
    bcr_portion_uuid: String,
    bcr_sample_barcode: String,
    bcr_sample_uuid: String,
    bcr_slide_barcode: String,
    bcr_slide_uuid: String,
    biospecimen_barcode_bottom: Number,
    birth_days_to: Number,
    center: String,
    center_id: Number,
    concentration: Number,
    dataType: String,
    date_of_creation: Date,
    date_of_shipment: Date,
    days_to_collection: Number,
    days_to_initial_pathologic_diagnosis: Number,
    er_status_by_ihc: String,
    er_status_ihc_Percent_Positive: String,
    ethnicity: String,
    exp_data_bed_url: String,
    exp_data_url: String,
    exp_metadata_url: String,
    experimental_protocol_type: String,
    ffpe_slide_uuid: String,
    form_completion_date: Date,
    gel_image_file: String,
    gender: String,
    her2_status_by_ihc: String,
    histological_type: String,
    history_neoadjuvant_treatment: String,
    history_other_malignancy: String,
    icd_10: String,
    icd_o_3_histology: String,
    icd_o_3_site: String,
    id: String,
    image_file_name: String,
    informed_consent_verified: String,
    initial_pathologic_dx_year:Number,
    initial_weight:Number,
    is_derived_from_ffpe: String,
    is_ffpe: String,
    last_contact_days_to: Number,
    lymph_nodes_examined: String,
    lymph_nodes_examined_count: Number,
    lymph_nodes_examined_he_count:Number,
    lymph_nodes_examined_ihc_count: Number,
    margin_status: String,
    margin_status_reexcision: String,
    meta_biotab_url: String,
    method_initial_path_dx: String,
    ncbi_build: Number,
    normal_tumor_genotype_match: String,
    oct_embedded: Boolean,
    pathology_report_file_name: String,
    pathology_report_uuid: String,
    patient_id: String,
    pcr_amplification_successful: String,
    percent_lymphocyte_infiltration:Number,
    percent_monocyte_infiltration: Number,
    percent_necrosis: Number,
    percent_neutrophil_infiltration: Number,
    percent_normal_cells: Number,
    percent_stromal_cells: Number,
    percent_tumor_cells: Number,
    percent_tumor_nuclei: Number,
    plate_column: Number,
    plate_id: String,
    plate_row: String,
    portion_number: Number,
    portion_sequence: Number,
    pr_status_by_ihc: String,
    pr_status_ihc_percent_positive: String,
    prospective_collection: String,
    quantity: Number,
    race: String,
    retrospective_collection: String,
    sample_type: String,
    sample_type_id: Number,
    section_location: String,
    seqPlatform: String,
    sequence_source: String,
    sequencer: String,
    source_center: Number,
    spectrophotometer_method: String,
    subportion_sequence: Number,
    surgery_for_positive_margins: String,
    surgical_procedure_first: String,
    tissue_source_site: String,
    tissue_status: String,
    tumor_description: String,
    tumor_sample_uuid: String,
    tumor_tag: String,
    tumor_tissue_site: String,
    vial_number: String,
    vital_status: String,
    volume: Number,
    weight: Number
});

var brcainfo=mongoose.model('brcainfo', brcaInfoSchema);

module.exports= brcainfo;